// Udemy/dev-web/exercicios-js/crud/frontend/src/app/views/home/home.component.ts
import { HeaderService } from './../../components/template/header/header.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit{


  constructor(private headerService: HeaderService) {
    headerService.headerData = {
      title: 'Inicio',
      icon: 'home',
      routerUrl: ''
    }
  }
  
  
  ngOnInit(): void {
      
  }
}

<mat-card class="home mat-elevation-z3">
    <mat-card-title class="title">
        Bem vindo!
    </mat-card-title>
    <mat-card-subtitle class="subtitle">
        Sistema para exemplicar a construção de um cadastro em Angular
    </mat-card-subtitle>
    </mat-card>

// Udemy/dev-web/exercicios-js/react/crud/frontend/src/components/home/home.jsx
import React from 'react'
import Main from '../template/main'

export default props => 
    <Main icon="home" title="Inicio"
            subtitle="Segundo Projeto do capítulo de React">
            <div className='display-4'>Bem Vindo!</div>
            <hr />
            <p className="mb-0">Sistema para exemplificar a construção de um cadastro desenvolvido em React!</p>
    </Main>
